import { Layout } from "@next-esm/next/server";
import type { Metadata } from "next";
import { t } from "@next-esm/next/i18n";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Layout>
      {t()}
      {children}
    </Layout>
  );
}
